db12_show/csvt06/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/show_author/$', 'blog.views.show_author'),
    url(r'^blog/show_book/$', 'blog.views.show_book'),
]

db12_show/blog/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=30)
    sex = models.CharField(max_length=30)
    age = models.CharField(max_length=30)

    def __unicode__(self):
	return self.name

class Book(models.Model):
    name = models.CharField(max_length=30)
    authors = models.ManyToManyField(Author)

    def __unicode__(self):
	return self.name

db12_show/blog/views.py
from django.shortcuts import render, render_to_response
from blog.models import Author, Book

# Create your views here.

def show_author(request):
    authors = Author.objects.all()
    return render_to_response('show_author.html', {'authors': authors})

def show_book(request):
    books = Book.objects.all()
    return render_to_response('show_book.html', {'books': books})

db12_show/blog/templates/show_author.html
<html>
    <head>
	<title></title>
    </head>

    <body>
	<hr />
	<h2> author with book </h2>
	<div>
	{% for author in authors %}
		<h3> {{author.name}} </h3>
		{% for book in author.book_set.all %}	
			<li>{{book}}</li>
		{% endfor %}
	{% endfor %}
	</div>

    </body>
</html>

db12_show/blog/templates/show_book.html
<html>
	<head>
	</head>
	
	<body>
		<div>
			{% for book in books %}
			<h3> {{book}} </h3>
				{% for author in book.authors.all %}
					<li>{{author}}</li>
				{% endfor %}
			{% endfor %}
		</div>
	</body>
</html>